// Blog posts. Body is an array of blocks: { p } paragraph, { h2 } heading,
// { ul } bullet list. Adapted from Scoreify source material.

export const posts = [
  {
    slug: "legitscript",
    title: "LegitScript certified vs whitelisted: the gap that costs you on Meta",
    category: "LegitScript",
    author: "Josh Richards",
    date: "2026-03-02",
    readTime: "4 min read",
    excerpt:
      "Most agencies sell “LegitScript-whitelisted” accounts that are nothing of the sort. Here’s the real difference, and why it decides your CPMs.",
    body: [
      { p: "Plenty of agencies advertise “LegitScript-whitelisted” ad accounts. Most don’t deliver what the term implies. Two very different outcomes hide behind one phrase, and the gap between them decides what you pay on Meta." },
      { h2: "Two things get called “LegitScript-whitelisted”" },
      { p: "What most providers actually deliver: they place your Business Manager into Meta’s Health & Wellness data classification. That grants permission to advertise in the vertical, but your accounts still sit inside Meta’s sensitive-category restriction layer. You get the same CPM penalties, pixel stripping, policy friction, and approval delays as any other health advertiser." },
      { p: "True whitelisting is different. It’s an entity-level designation that recognizes verified health advertisers on Meta’s backend, pairing LegitScript certification with high-trust credentialing infrastructure." },
      { h2: "Why the difference shows up in your numbers" },
      { ul: [
        "Lower CPMs, outside the healthcare auction penalty",
        "Pixel data retained instead of stripped",
        "Audience-building features standard health accounts can’t touch",
        "Policy review that treats you as a credentialed partner, not a category risk",
        "Fewer creative rejections on the exact same ads",
      ] },
      { h2: "Why self-submission rarely works" },
      { p: "You can submit LegitScript credentials yourself through Meta’s authorization panel. In regulated verticals that process usually takes months and often fails outright. Even when it succeeds, you get basic authorization, not whitelisting. Your trust tier doesn’t move." },
      { h2: "How Scoreify handles it" },
      { p: "Scoreify runs Meta accounts with entity-level LegitScript whitelisting, submitted through high-trust agency infrastructure rather than the standard authorization channel. You start at the tier most advertisers never reach." },
    ],
  },
  {
    slug: "hiva-tier",
    title: "HiVA-tier: the hidden trust score behind your Meta performance",
    category: "HiVA-tier",
    author: "Rushee Ramchuran",
    date: "2026-03-10",
    readTime: "5 min read",
    excerpt:
      "Two identical campaigns, one at $20 CPM and one at $60. The difference is a score Meta never shows you.",
    body: [
      { p: "Two advertisers run the same regulated offer. Same creative, same targeting, same landing page. One pays $20 CPM, the other $60. The difference isn’t skill. It’s the HiVA-tier of the infrastructure underneath." },
      { h2: "What HiVA-tier is" },
      { p: "HiVA stands for High Value Asset, Meta’s internal trust classification for Business Managers, ad accounts, Pages, pixels, and creatives. There are four tiers:" },
      { ul: [
        "Platinum: preferential auction positioning, lower CPMs, smoother delivery, faster learning, higher spend caps",
        "Gold: strong assets running with little friction",
        "Silver: where most advertisers sit, with periodic delivery and scaling limits",
        "Bronze: a de-facto shadowban where Learning Limited never resolves",
      ] },
      { p: "The score never appears in Ads Manager or the account quality dashboard, yet it shapes how aggressively you compete in the auction and what you pay per impression." },
      { h2: "Why it matters more in regulated health" },
      { p: "Since Meta’s January 2025 healthcare reclassification, regulated advertisers lost access to lower-funnel signals like Purchase and Subscribe. With less outcome data to read, Meta leans harder on HiVA-tier to decide who to trust. That’s why identical campaigns land at different CPMs and ROAS." },
      { h2: "Why Platinum is hard to reach on your own" },
      { ul: [
        "You can’t optimize a metric you can’t see",
        "The lowest-tier asset caps the whole structure, and clean assets degrade within 30 to 90 days when added to a compromised account",
        "Downgrades happen fast, upgrades take sustained clean signal and escalation access most operators don’t have",
      ] },
      { h2: "How Scoreify handles it" },
      { p: "Scoreify delivers accounts at Platinum HiVA-tier from day one, using aged Business Managers with documented health history and no inherited restrictions, then holds that tier with daily backend monitoring." },
    ],
  },
  {
    slug: "compliance",
    title: "Meta won’t tell you when your account starts slipping",
    category: "Compliance",
    author: "Rushee Ramchuran",
    date: "2026-03-10",
    readTime: "4 min read",
    excerpt:
      "Health accounts rarely die suddenly. They decay through signals Meta never surfaces, until your CPMs have already moved.",
    body: [
      { p: "Regulated health accounts rarely get shut off overnight. They decay. Feedback scores tick down, hidden warnings pile up, restrictions switch on quietly, and none of it shows up in Ads Manager. By the time your metrics move, the downgrade already happened." },
      { h2: "The signals Meta hides" },
      { p: "Meta tracks far more than it shows you:" },
      { ul: [
        "HiVA tier (trust classification)",
        "ACE warnings (adversarial control flags)",
        "CAR score (creative-level trust)",
        "Feedback score (an auction lever post-Andromeda)",
        "Restriction history (soft enforcement count)",
        "Policy compliance trend",
        "Pixel data quality",
      ] },
      { p: "Together these drive delivery, auction position, and how aggressively Meta enforces against you." },
      { h2: "Why most advertisers catch it too late" },
      { ul: [
        "The metrics live outside Ads Manager",
        "Several can decline at once and trigger a downgrade with no notification",
        "You only find out after CPMs rise and delivery slows",
      ] },
      { h2: "How Scoreify handles it" },
      { p: "Scoreify monitors 43+ backend signals daily. When something moves the wrong way, we act within 24 hours through creative changes, page-level fixes, or policy escalation, before the problem reaches your reporting." },
    ],
  },
  {
    slug: "policy",
    title: "Why your compliant ads still get rejected on Meta",
    category: "Policy",
    author: "Josh Richards",
    date: "2026-03-10",
    readTime: "4 min read",
    excerpt:
      "You followed the rules and still got rejected. The problem is category-level risk scoring, not your ad.",
    body: [
      { p: "Operators in compounded GLP-1, telehealth, and online pharmacy get rejected at far higher rates than other advertisers, even when they follow the rules. Meta treats whole categories as default risks instead of judging advertisers one at a time." },
      { h2: "What’s really happening on rejection" },
      { p: "Review leans on automated pattern detection more than human policy review. Common triggers:" },
      { ul: [
        "Visuals that look like before/after comparisons",
        "Copy with restricted health terms",
        "URLs whose event names read as health identifiers",
        "Page parameters that suggest sensitive data",
        "References to specific molecules",
      ] },
      { p: "Most flags are technically appealable. The appeal is where it falls apart." },
      { h2: "Why standard appeals usually fail" },
      { p: "Appeals route back through the same automated queue that rejected you, with the same models and thresholds. You get a generic denial in 24 to 48 hours with no explanation, your rejection history grows, and similar creative gets flagged more easily next time." },
      { h2: "What direct escalation looks like" },
      { p: "High-trust agency accounts reach escalation channels you can’t get through standard appeals. These are relationship-based pathways to Meta’s policy team, built over years of credentialed account management. Escalated creative gets judged on advertiser credibility and history rather than category default." },
      { h2: "How Scoreify handles it" },
      { p: "Every Scoreify account gets direct policy escalation, pre-launch pattern detection, and PHI-detection updates that track Meta’s evolving systems." },
    ],
  },
  {
    slug: "pixel",
    title: "Why your pixel data gets stripped in Meta’s health category",
    category: "Research",
    author: "Josh Richards",
    date: "2026-03-10",
    readTime: "4 min read",
    excerpt:
      "Your events look like they fire. Meta just isn’t using them. Here’s what gets stripped and why.",
    body: [
      { p: "Health advertisers hit a strange disconnect. Your pixel events look like they fire correctly in reporting, but the algorithm doesn’t actually use them. Costs climb and audience modeling stays weak." },
      { h2: "What Meta strips in health and wellness" },
      { p: "Since the January 2025 healthcare reclassification, GLP-1, telehealth, online pharmacy, and hormone therapy sit in a restricted data zone:" },
      { ul: [
        "Conversion events (Purchase, Add to Cart, Subscribe) get blocked or removed during ingestion",
        "User identifiers are removed, so conversions can’t attribute to individuals",
        "Behavioral signals can’t feed lookalikes",
        "PHI detection flags event parameters that look health-related, regardless of the actual content",
      ] },
      { h2: "Why the usual workarounds fail" },
      { p: "Conversions API, event renaming, and custom configs help for a while. Meta’s detection evolves quarterly, so approaches that worked last quarter start tripping filters within months." },
      { h2: "Why credentialing changes the result" },
      { p: "Whitelisted accounts at Platinum HiVA-tier run on different auction logic. The same pixel firing through credentialed infrastructure produces better results than a standard health account, while staying compliant." },
      { h2: "How Scoreify handles it" },
      { p: "Scoreify runs pre-credentialed accounts and reviews events continuously to stay compatible with current detection patterns." },
    ],
  },
  {
    slug: "client-dashboard",
    title: "Inside the Scoreify client dashboard",
    category: "Product",
    author: "Josh Richards",
    date: "2026-03-10",
    readTime: "3 min read",
    excerpt:
      "Most agencies keep you in the dark. Every Scoreify account comes with a live dashboard of the work underneath.",
    body: [
      { p: "Scoreify works with high-spend operators in regulated health. Instead of the usual black-box agency relationship, every client gets daily access to a live dashboard showing exactly what’s happening with their accounts." },
      { h2: "What the dashboard shows" },
      { ul: [
        "Spend tracking: daily, weekly, and monthly against your prepaid balance",
        "Deposit balance and runway: funds left and how long they cover",
        "Real-time fees: transparent rate, base, and daily owed",
        "Account status: LegitScript expiration, verification, HiVA tier, and protection days",
        "Daily work logs: timestamped policy checks, account reviews, and compliance actions",
      ] },
      { h2: "Account and financial views" },
      { p: "Account pages show verification and policy monitoring with a compliance heatmap and a timestamped global activity log. The wallet view shows prepaid balance, deposit history, 30-day spend and fee analysis, runway projection, and monthly breakdowns." },
      { h2: "Why we built it" },
      { p: "Two reasons. You should be able to check your infrastructure status anytime. And the dashboard makes the compliance work visible, the work that stays hidden inside standard ad management tools." },
      { h2: "How Scoreify handles it" },
      { p: "The dashboard ships with every account. It isn’t a premium add-on." },
    ],
  },
];

export function getPost(slug) {
  return posts.find((p) => p.slug === slug);
}
